SELECT 
  SSP_ID,
  SSP_DESC,
  CMNTY_ID,
  SSP_START_DATE,
  SSP_END_DATE,
  SSP_MSG_URL,
  SSP_MSG_TEXT_CLOB,
  CREAT_BY,
  UPDATE_BY
FROM (
  SELECT 
    SSP_ID,
    SSP_DESC,
    CMNTY_ID,
    SSP_START_DATE,
    SSP_END_DATE,
    SSP_MSG_URL,
    SSP_MSG_TEXT_CLOB,
    CREAT_BY,
    UPDATE_BY,
    CREAT_TM,
    ROW_NUMBER() OVER (PARTITION BY SSP_ID ORDER BY CREAT_TM DESC) AS sort_no
  FROM WPA_SSP
  WHERE CREAT_TM > SYSDATE - 30
) ssp_dtls
WHERE ssp_dtls.sort_no = 1
ORDER BY ssp_dtls.CREAT_TM DESC;
